* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ *
* TOKEN CONSTANTS
* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ *

#Define		TOKEN_UNKNOWN  		0
#Define		TOKEN_NUMBER		1
#Define		TOKEN_STRING  		2
#Define		TOKEN_KEYWORD  		3
#Define		TOKEN_WORD			4
#Define		TOKEN_COMMA  		5
#Define		TOKEN_COMMENT  		6
#Define		TOKEN_NULL			7
#Define		TOKEN_CREATE		8
#Define		TOKEN_JSON			9
#Define		TOKEN_OBJECT		10
#Define		TOKEN_FROM			11
#Define		TOKEN_FILE			12
#Define		TOKEN_CONNECTION	13
#Define		TOKEN_METHOD		14
#Define		TOKEN_GET			15
#Define		TOKEN_POST			16
#Define		TOKEN_HTTP			17
#Define		TOKEN_REQUEST		18
#Define		TOKEN_FOR			19
#Define		TOKEN_CURSOR		20
#Define		TOKEN_IN			21
#Define		TOKEN_SCREEN		22
#Define		TOKEN_TO			23
#Define		TOKEN_PRINT			24
#Define		TOKEN_URL			25
#Define		TOKEN_ADD			26
#Define		TOKEN_HEADER		27
#Define		TOKEN_VALUE			28
#Define		TOKEN_WITH			29
#Define		TOKEN_BODY			30

* TOKEN STATE
#Define		TOKEN_STATE_NUMBER 		TOKEN_NUMBER
#Define		TOKEN_STATE_DEFAULT		99
#Define		TOKEN_STATE_WORD 		TOKEN_WORD
#Define		TOKEN_STATE_STRING		TOKEN_STRING
#Define		TOKEN_STATE_COMMENT		TOKEN_COMMENT